### ISSUE TITLE
Possible GPL violation with the use of the goldberg library

### ISSUE THREAD

**Issue by FSMaxB** [0xor0ne/debugoff#1]
The `goldberg` library is licensed as GPL-3.0 and if I understand that correctly, this would force you to license `debugoff` as GPL-3.0 as well because of the Copyleft.

I'm not sure if it's possible to license `debugoff` in such a way that it is only GPL if the `obfuscate` feature is enabled and/or if using `obfuscate` only counts as using the output created by it (the same way that the machine code produced by GCC doesn't count as a derived work of GCC).

But you should definitely look into the specifics of the licensing situation here and potentially remove the dependency on `goldberg`.

**Comment by 0xor0ne** [comment]
Hi @FSMaxB,

for the moment I updated to version 0.2.0 and changed the main licence to GPL-3.0 (the code can still be used with MIT license when `obfuscate` feature is not used).

In the readme I stated the following:

> Licensed under:
>
> * GPL-3.0 when `obfuscate` feature is enabled;
> * MIT when `obfuscate` feature **IS NOT** enabled;

Do you think this could work to avoid GPL violation?

**Comment by FSMaxB** [comment]
> Do you think this could work to avoid GPL violation?

I am not sure to be honest. I just noticed in passing that the `goldberg` dependency is GPL and thought I better let you know.

**Comment by 0xor0ne** [comment]
> I just noticed in passing that the `goldberg` dependency is GPL and thought I better let you know.

Thanks, appreciate it.

For now I'm closing this issue. I will look for more information and if I find out this is not a suitable solution I will just drop the MIT license (at least until I will have a proper replacement for `goldberg`).
